version: '2'
networks: 
  tasks:
    external: true
services:
  agent:
    image: 'johanhenriksson/pipeline-agent'
    build: './agent'
    hostname: 'agent'
    networks:
      - default
      - tasks
    ports:
      - '1337:1337'
    volumes:
      - './agent/src:/app/src:ro'
      - './agent/data:/app/data'

  dash:
    image: 'johanhenriksson/pipeline-dash'
    build: './dash'
    hostname: 'dash'
    networks:
      - default
      - tasks
    ports:
      - '1339:1339'
    volumes:
      - './dash/src:/app/src:ro'