version: '2'
networks: 
  tasks:
    external: true
services:
  agent:
    image: 'johanhenriksson/pipeline-agent'
    build: './agent'
    hostname: 'agent'
    networks:
      - default
      - tasks
    ports:
      - '1337:1337'
      - '1338:1338'
    volumes:
      - './agent/src:/app/src:ro'
      - './agent/data:/app/data'