version: 1
pipeline:
  image: docker.backtick.se/core

  cluster:
    default: docker
    docker:
      network: tasks
      hello: world
    kubernetes:
      namespace: default
      domain: cluster.backtick.se
    api:
      url: http://localhost:63258
      ws_url: http://localhost:1337
