name: Tests

on: [push]

jobs:
  run_tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Build task base image
      run: docker build . --file Dockerfile --tag cowait/task

    - name: Create tasks network
      run: docker network create tasks
      
    - name: Test Package
      run: bash ./test.sh

    - name: Test Examples
      run: bash ./test.sh --examples
